# This is a basic workflow to help you get started with Actions
name: jboss
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ lab ]
  pull_request:
    branches: [ lab ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: check path 
        run: |
             ls -lta
#      - name: build img             
#        run: |
#              cd FE/
#              sudo docker build -f Dockerfile-FE --no-cache -t jboss/wildfly:8.1.0.Final-FE .
#              cd ../BE/
#              sudo docker build -f Dockerfile-BE --no-cache -t jboss/wildfly:24.0.0.Final-BE .
#              cd ../

      - name: deploy be1
        run: |
             if [ ! -z "$(docker ps | grep jboss-be1)" ];then
              sudo docker stop jboss-be1
              sudo docker rm jboss-be1
              sudo docker run -d --network my-net --name jboss-be1 -p 30180:8080 redhat8-0:5000/jboss/wildfly:24.0.0.Final-BE
             else
              sudo docker run -d --network my-net --name jboss-be1 -p 30180:8080 redhat8-0:5000/jboss/wildfly:24.0.0.Final-BE
             fi

      - name: deploy fe
        run: |
             if [ ! -z "$(docker ps | grep jboss-fe)" ];then
              sudo docker stop jboss-fe
              sudo docker rm jboss-fe
              sudo docker run -d --network my-net --name jboss-fe -p 30080:8080 redhat8-0:5000/jboss/wildfly:8.1.0.Final-FE
             else
              sudo docker run -d --network my-net --name jboss-fe -p 30080:8080 redhat8-0:5000/jboss/wildfly:8.1.0.Final-FE
             fi

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
#      - name: test-be1
#        run: curl 127.0.0.1:30180
      - name: test-fe
        run: |
             curl 127.0.0.1:30080/getBE > /tmp/fe-getBE.tmp
             curl 127.0.0.1:30180 > /tmp/be1.tmp
      - name: stop-container
        run: |
             sudo docker stop jboss-fe && sudo docker rm jboss-fe
             sudo docker stop jboss-be1 && sudo docker rm jboss-be1

